### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by Fuyukai** [PurpleMyst/epython#5]
Exception handling is a pretty key concept. This is a tracking issue for everything related to it.

- [ ] Being able to throw exceptions and unwind the stack
- [ ] `try`/`except` statements
- [ ] Exception objects and hierachy
- [ ] User-defined exceptions
