### ISSUE TITLE
OO support

### ISSUE THREAD

**Issue by Fuyukai** [PurpleMyst/epython#6]
OO support is a critical part of Python.

- [ ] Basic object support (classes)
- [ ] Magic class methods (`__init__` etc)
- [ ] Types
- [ ] First-class object support (everything is an object)
- [ ] Slotted objects

And so on.
