### ISSUE TITLE
Import system

### ISSUE THREAD

**Issue by PurpleMyst** [PurpleMyst/epython#8]
Adding an import system is important, due to it being one of python's biggest strengths.

- [ ] Basic module support (variables, functions, ...)
- [ ] Module-specific variables (`__name__`, ...)
- [ ] Builtin modules (`math`, ...)
- [ ] OS-specific modules (`os`, `sys`, ...)
